const actionTypes = {
  // Entity tags
  UPDATE_ENTITY_TAGS: 'UPDATE_ENTITY_TAGS',
  UPDATE_ENTITY_TAGS_SUCCESS: 'UPDATE_ENTITY_TAGS_SUCCESS',
  UPDATE_ENTITY_TAGS_FAILURE: 'UPDATE_ENTITY_TAGS_FAILURE',
  UPDATE_TAG_ON_ENTITY: 'UPDATE_TAG_ON_ENTITY',
};

export default actionTypes;
